# Generated by Django 3.2.8 on 2021-10-20 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_from",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be 3 uppercase letters long",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "currency_to",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be 3 uppercase letters long",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=5, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
